apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: distcc-server
spec:
  selector:
    matchLabels:
      app: distcc
  template:
    metadata:
      labels:
        app: distcc
    spec:
      containers:
      - name: distcc
        image: 248189943700.dkr.ecr.eu-west-2.amazonaws.com/stb-my-ecr-repo:kernel-image-worker  # Imagen de Distcc
        ports:
        - containerPort: 3632  # Puerto para Distcc
        env:
        - name: DISTCC_HOSTS
          value: "distcc-server:3632"  # Conectar todos los nodos a este servidor
---
apiVersion: v1
kind: Service
metadata:
  name: distcc-server
spec:
  ports:
  - port: 3632
  selector:
    app: distcc
