apiVersion: batch/v1
kind: Job
metadata:
  name: kernel-build
  labels:
    job-name: kernel-build
spec:
  template:
    spec:
      containers:
      - name: kernel-build
        image: 248189943700.dkr.ecr.eu-west-2.amazonaws.com/stb-my-ecr-repo:kernel-image-job
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: aws_secret_access_key
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: aws_session_token
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: aws_region
        command:
        - /bin/sh
        - c
        - |
          make -j$(nproc) CC=distcc gcc CXX=distcc g++ &&
          tar -czvf /kernel-src/kernel.tar.gz /path/to/kernel-binaries &&
          aws s3 cp /kernel-src/kernel.tar.gz s3://proyect-2-stb-devops-bucket/kernel.tar.gz
      restartPolicy: Never
      restartPolicy: Never
  backoffLimit: 4
