name: Build and Push Docker Image to ECR
on:
    push:
      branches:
        - main
        - develop
      paths:
        - 'aplicacion/**'
        - 'Dockerfile.server'
        - 'Dockerfile.worker' 
jobs:
  build_worker:
    runs-on: ubuntu-latest
    env:
        ECR_REPO: "248189943700.dkr.ecr.eu-west-2.amazonaws.com/stb-my-ecr-repo"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
   
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }} # Referencia a la zona
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}   # Referencia al secreto
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   # Referencia al secreto
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Si es necesario (solo para credenciales temporales)
      
      - name: Loguearse en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
          registry-type: private
 
      - name: Build Docker image
        run: |

          docker build -t worker-go -f Dockerfile.worker .

          docker tag worker-go:latest $ECR_REPO:worker-go

          docker push $ECR_REPO:worker-go

  build_server:
    runs-on: ubuntu-latest
    env:
        ECR_REPO: "248189943700.dkr.ecr.eu-west-2.amazonaws.com/stb-my-ecr-repo"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
   
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }} # Referencia a la zona
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}   # Referencia al secreto
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   # Referencia al secreto
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Si es necesario (solo para credenciales temporales)
      
      - name: Loguearse en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
          registry-type: private
 
      - name: Build Docker image
        run: |

            docker build -t server-go -f Dockerfile.server .

            docker tag server-go:latest $ECR_REPO:server-go

            docker push $ECR_REPO:server-go


