name: Build and Push Docker Image to ECR
on:
    workflow_dispatch: 
jobs:

  build_image_kernel:
    runs-on: ubuntu-latest
    env:
        ECR_REPO: "248189943700.dkr.ecr.eu-west-2.amazonaws.com/stb-my-ecr-repo"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
   
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }} # Referencia a la zona
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}   # Referencia al secreto
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   # Referencia al secreto
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Si es necesario (solo para credenciales temporales)
      
      - name: Loguearse en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
          registry-type: private
 
      - name: Build Docker image
        run: |

            docker build -t kernel-image -f Dockerfile.kernel.compile .

            docker tag kernel-image:latest $ECR_REPO:kernel-image

            docker push $ECR_REPO:kernel-image


