name: JOB= Build and Push Kernel Image to ECR

on:
  workflow_dispatch: 

jobs:
  build_image_kernel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rol: [job]  # Los valores posibles para el "job"

    env:
      ECR_REPO: "248189943700.dkr.ecr.eu-west-2.amazonaws.com/stb-my-ecr-repo"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }} # Referencia a la zona
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}   # Referencia al secreto
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   # Referencia al secreto
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Si es necesario (solo para credenciales temporales)

      - name: Loguearse en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
          registry-type: private

      - name: Build Docker image
        run: |
          IMAGE_NAME="kernel-image-${{ matrix.rol }}"  # Usamos job y worker para formar el nombre
          echo "Building Docker image: $IMAGE_NAME"
          
          docker build -t $IMAGE_NAME -f Dockerfile.kernel.${{ matrix.rol }} .
          docker tag $IMAGE_NAME:latest $ECR_REPO:$IMAGE_NAME
          docker push $ECR_REPO:$IMAGE_NAME
