name: Kernel Build & Release

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}


    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_DEFAULT_REGION }} --name mi-cluster-Grupo2

    - name: Deploy kernel build pod to EKS
      run: |
        kubectl apply -f kernel-build-pod.yml  # Desplegar un pod con la imagen para compilar el kernel
    - name: Deploy kernel build pod to EKS
      run: |
          kubectl apply -f job/secret.yml  # Desplegar un pod con la imagen para compilar el kernel
    - name: Deploy kernel build job to EKS
      run: |
            kubectl apply -f job/kernel-build-job.yml
        

    - name: Wait for the build to finish
      run: |
        # Buscamos el nombre del Job utilizando su etiqueta
        job_name=$(kubectl get jobs -l job-name=kernel-build --no-headers -o custom-columns=":metadata.name" | head -n 1)
        if [ -n "$job_name" ]; then
        kubectl wait --for=condition=complete job/$job_name --timeout=600s
        else
        echo "Job kernel-build not found."
        exit 1
        fi

