name: Kernel Build & Release

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}


    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_DEFAULT_REGION }} --name mi-cluster-Grupo2

  build_kernel:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Check out the kernel source code
      uses: actions/checkout@v4
      with:
        repository: "torvalds/linux"
        ref: "master"
        fetch-tags: "v6.13"

    - name: Deploy kernel build pod to EKS
      run: |
        kubectl apply -f kernel-build-pod.yml  # Desplegar un pod con la imagen para compilar el kernel
    - name: Deploy kernel build pod to EKS
      run: |
          kubectl apply -f job/secrets.yml  # Desplegar un pod con la imagen para compilar el kernel
    - name: Deploy kernel build job to EKS
      run: |
            kubectl apply -f job/kernel-build-job.yml
        

    - name: Wait for the build to finish
      run: |
        kubectl wait --for=condition=complete job/kernel-build-job --timeout=600s

